# Generated by Django 5.1.5 on 2025-04-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permis_Conduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('permis_conduite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permis', to='LocationV.permis_conduite')),
            ],
        ),
    ]
