# Generated by Django 5.1.5 on 2025-04-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0002_permis_conduite_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='LocationV.statut'),
        ),
    ]
