# Generated by Django 5.1.5 on 2025-04-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0003_alter_voiture_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='permis_conduite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permis', to='LocationV.permis_conduite'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='statut',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='LocationV.statut'),
        ),
    ]
