# Generated by Django 5.1.5 on 2025-04-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0004_alter_client_permis_conduite_alter_voiture_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='LocationV.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='LocationV.voiture')),
            ],
        ),
    ]
