# Generated by Django 5.1.5 on 2025-04-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0006_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='LocationV.reservation'),
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_vehicule', models.CharField(max_length=50)),
                ('frais_supplementaire', models.TextField()),
                ('kilometrage_final', models.IntegerField()),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voit', to='LocationV.voiture')),
            ],
        ),
    ]
