# Generated by Django 5.1.5 on 2025-04-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0008_alter_voiture_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_reparation', models.DateField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reparateur', models.CharField(max_length=100)),
                ('est_terminee', models.BooleanField(default=False)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='v', to='LocationV.voiture')),
            ],
        ),
    ]
