# Generated by Django 5.1.5 on 2025-04-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocationV', '0009_reparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panne', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reparation',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_panne', to='LocationV.type_panne'),
        ),
    ]
