# Generated by Django 5.1.5 on 2025-04-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormUP', '0002_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='FormUP.cours')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_donnee', to='FormUP.formateur')),
            ],
        ),
    ]
