# Generated by Django 5.1.5 on 2025-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_livre_disponible_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='avis',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
